spring.application.name=financetracker

spring.datasource.url=postgresql://personal_fiance_tracker_db_user:SM4DUB4bPwBJPdsEara26QCMcmFPP9LX@dpg-d74d0m9r0fns73ctkh6g-a/personal_fiance_tracker_db
spring.datasource.username=personal_fiance_tracker_db_user
spring.datasource.password=SM4DUB4bPwBJPdsEara26QCMcmFPP9LX
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect  <-- optional, can remove
